---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellyfin
            version: 20.6.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-jellyfin"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: real-ip
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: stream.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 0 * * *
        media:
          enabled: true
          type: nfs
          path: ${STREAM_NFS_PATH}
          server: ${NAS_IP}
          mountPath: /Media
      workload:
        main:
          podSpec:
            runtimeClassName: "nvidia"
            containers:
              main:
                resources:
                  limits:
                    nvidia.com/gpu: 1
      autodiscovery:
        enabled: true