---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.13.17
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
    workload:
      main:
        replicas: 1
        strategy: RollingUpdate
    blocking:
      blacklist:
      - name: blocked
        lists:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://dl.red.flag.domains/pihole/red.flag.domains.txt
      clientGroupsBlock:
        - name: default
          groups:
            - blocked
    k8sgateway:
      domains:
      - domain: "${DOMAIN_0}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
    defaultUpstreams:
    - "https://1.1.1.1/dns-query"
    bootstrapDns:
      ips: []
      upstream: "1.1.1.1"
    queryLog:
      type: ""
    configmap:
      dashboard:
        enabled: false
      datasource:
        enabled: false
    cnpg:
      main:
        enabled: false
    metrics:
      main:
        enabled: false