apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: amd-gpu-operator
    namespace: amd-gpu-operator
spec:
    interval: 5m
    chart:
        spec:
            chart: gpu-operator-charts
            version: 1.2.0
            sourceRef:
                kind: HelmRepository
                name: rocm
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: