apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/amd-gpu/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

