apiVersion: v1
kind: Pod
metadata:
  name: fsck-helper
  namespace: fsck-ns
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-control-1  # Replace with actual node name
  hostPID: true
  containers:
  - name: fsck
    image: alpine
    command:
      - sh
      - -c
      - sleep 1h  # gives you time to exec in
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /host/dev
  volumes:
  - name: dev
    hostPath:
      path: /dev
