apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermes
  namespace: hermes
spec:
  chart:
    spec:
      chart: app-template
      version: 18.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  interval: 5m
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    image:
      pullPolicy: Always
      repository: nousresearch/hermes-agent
      tag: latest
    persistence:
      hermes-data:
        accessMode: ReadWriteOnce
        enabled: true
        mountPath: /opt/data
        size: 5Gi
        type: pvc
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      pod:
        fsGroup: 0
    service:
      main:
        ports:
          main:
            enabled: true
            port: 8642
            protocol: http
            targetPort: 8642
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
              - gateway
              - run
              env:
                API_SERVER_HOST: 0.0.0.0
                API_SERVER_KEY: "${AI_API_KEY}"
                HERMES_HOME: /opt/data
                HERMES_MODEL: qwen3.5:4b-ext
                OPENAI_API_KEY: ollama
                OPENAI_BASE_URL: http://ollama-api.ollama.svc.cluster.local:11434/v1
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 512Mi
          initContainers:
            init-config:
              command:
              - sh
              - -c
              - |
                /opt/hermes/.venv/bin/hermes config set model.provider openai-compatible
                /opt/hermes/.venv/bin/hermes config set model.name qwen3.5:4b
                /opt/hermes/.venv/bin/hermes config set model.base_url http://ollama-api.ollama.svc.cluster.local:11434/v1
                /opt/hermes/.venv/bin/hermes config set model.context_length 262144

                echo "OPENAI_API_KEY=ollama" >> /opt/data/.env
                echo "OPENAI_BASE_URL=http://ollama-api.ollama.svc.cluster.local:11434/v1" >> /opt/data/.env
                echo "HERMES_MODEL=qwen3.5:4b" >> /opt/data/.env
              enabled: true
              env:
                HERMES_HOME: /opt/data
              image:
                repository: nousresearch/hermes-agent
                tag: latest
              type: init
              volumeMounts:
              - mountPath: /opt/data
                name: hermes-data