apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webhook
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/flux-system/webhook/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

