apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermes
  namespace: ai
spec:
  chart:
    spec:
      chart: app-template
      version: 18.14.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  interval: 5m
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    image:
      pullPolicy: Always
      repository: nousresearch/hermes-agent
      tag: latest
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      pod:
        fsGroup: 1000
    service:
      main:
        ports:
          main:
            enabled: true
            port: 8642
            protocol: http
            targetPort: 8642
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - gateway
                - run
              env:
                API_SERVER_HOST: 0.0.0.0
                API_SERVER_KEY: "${AI_API_KEY}"
                HERMES_HOME: /opt/data
                OPENAI_API_KEY: ollama
                OPENAI_BASE_URL: http://ollama-api.ai.svc.cluster.local:11434/v1
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 512Mi
    persistence:
      hermes-data:
        accessMode: ReadWriteOnce
        enabled: true
        mountPath: /opt/data
        size: 5Gi
        type: pvc