apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellystat
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellystat
            version: 5.5.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-jellystat"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: stat.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      cnpg:
        main:
          cluster:
            singleNode: true
            credentials: minio
            scheduledBackups:
              - name: daily-backup
                schedule: "0 5 0 * * *"
                backupOwnerReference: self
                immediate: true
                suspend: false
          recovery:
            method: object_store
            credentials: minio
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 0 * * *