apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:OgVz7cqO+YBKHAYAFt/cXY2eaKdoogMU2hBXIQfi1xprRBxSfJi0yEioYijRCZUSG+ei93q7fPlEsf/Tb3cDlS4=,iv:ndPz9rVK60sHAWfT6vfu7degDqujWcoHLwbSntbIF9w=,tag:HuQhjh3VUpHcJPJTGq0qdQ==,type:comment]
    #ENC[AES256_GCM,data:Ow7RibF4Sb83sZc6TI6QU4+IBEocYIPdEW2juHBM1yRvdGuD1j5WvFbPQss=,iv:zcs13hdIS+FBvhByhOe/iqfYX1USry5ew/1svJPjPKo=,tag:DiuMFSBgmtIEwWpwh7NPZg==,type:comment]
    VIP: ENC[AES256_GCM,data:gkt+csZI/HKKSrzsLA==,iv:kdcJbC0p7ZHtLJAZIL0SlXwMlNw83pFHvunYbTicius=,tag:JV3VAvl08liUlvDPsqX83Q==,type:str]
    #ENC[AES256_GCM,data:mNFN50D6MAEvcjxWChzqsOdzXi3j81h31X9Q,iv:bbOs049dxa8HXrRGKgulLKJL94iIzSvrx0KyrRHkcJ0=,tag:iua0hh82MKM3pz1/VF9evg==,type:comment]
    #ENC[AES256_GCM,data:133bRn/68+sJT1Ml/1GOA+Fa6NNvvzQABbhJ3tfQuXMvwgX4LQF9ntv2GX976/OkaFKSn9by8kElTJThsYXbrq9URmAEUOEMszJS1N+yVmRG6HOwK6HhbaU=,iv:vqtZlzXGI2/mwj/iGbqf3hwdotgWsUQOUFvPZrcLpQs=,tag:AiUe1RUYh84jvn8fGyKyOg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:m/s0fbQVESiSgLpznw==,iv:rzVFEzDCRQwyH0VIy4llsUc9yRLqR8YkAjE2Yryg9kU=,tag:dcTZiYfRKwKe80Feyy0sgw==,type:str]
    #ENC[AES256_GCM,data:7IXL0D+vmYNAl31vYY38idusQfCiZ8O5R9JiEUP66ZMaDg==,iv:QLA3lfFeqz1QTLQ7FoU7JhXFJXIFjtG7ughKldy5AZo=,tag:cSD4RWu1xVocTrx2tUoc8g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:2putQSJR2fW9jWcx9A==,iv:SVMoV8IKeOzoiT5/SFcXoLfe/XQh8dNKI7nFo9/LpnE=,tag:yF+PZi4zyYk7sqsrRUyjzA==,type:str]
    #ENC[AES256_GCM,data:K2x3V4DN8Ldob10IHbNnPSPB4ELwaQN3tkL9F/WO46TenqOvwUQpHsNi21hixgI=,iv:nQXtCMKQD663jL8UmBvo1awi19MhMJFRZy9DuSztpoo=,tag:molOKcC4fk3iBXF4YY8TCw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:+tJHJu3cq92RIWkjeI1/eKpUtRvbhbcI2ihr,iv:q8m9sb51LjqziR8sXoAyCxnaFRi06QMEQ/j/chrvmb0=,tag:qZCWGSuw28/KU89Q/Bn3dg==,type:str]
    #ENC[AES256_GCM,data:haWspvj09GNTFCtuajLYfaM5z3NRyBkR0Pa5y/qs4+0UT2SfYJT/KR7BwbtZSD0/oZT6NrhbP3C/58QHPi1kfyLoHWBS9U90lC5FYdcqMSlW4g==,iv:D3MxdgoZiX76XcZcpFHmKjnd3pfbtc/jxi4T6xaOXU4=,tag:1aygoCcnTSfLtCLZ56FBCw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:70UHGIieSxorwcUwOg==,iv:TYEhA+MG+UUonZHuJLuDkqb/+aUPFyhXh2MiPrlwWKM=,tag:2d9760If7x2tEfe1FB56Xg==,type:str]
    #ENC[AES256_GCM,data:5Z5NXV4tuJz+TgvWZibJW4W5YpXHC5uL1IcSwOAy72pM,iv:bu8D9mthg4ufpjIKirSRufxoFa77FdPkW0ehLtx58D0=,tag:7n/M8VgS+7qHjHQrqTh6uw==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:5KvXvyEEkU3YSwfCuw==,iv:g5i30nzQsIGL1SMLH1HXj9mX6QFsrbAU+mXHLhr5E6Y=,tag:hX4L4yDel8FNqcZeEpNK+w==,type:str]
    #ENC[AES256_GCM,data:vkTc0JuBh8kIFmUimGf6PxgXCAFotgrmlWtxQTmfuwQs1xbOL5eVwvQoJEj++Nwp5utgNuFL/gzpyesYOr7qQHUEeHFJzZU3srpJhiZ+Eek=,iv:HwbYlmNIuiQqTHEBmWEIyTsgDkQgngFvxkGARDpnziY=,tag:Ej8he1VYhQg+FOp04T8ZOg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:mpfaHWvsIX/mbmF4Yg==,iv:MWNnGzeobaJOPY/6ApWKXPeSa04vrDnX9UBeAWeg5h4=,tag:UpwZcvFXTIuausvfku/tsQ==,type:str]
    #ENC[AES256_GCM,data:nnBp6PbYUeyec1XZFWPcIIgk/2ywDq5IPdeLWWQAYCYFpSDeBej+bv+lXKAXu0myRPuaWYWOLlPODzq6qEjrFiUEtmRbwMoQtHVtS0iXzoJDORMuxxOw,iv:EBpiaJSwS9WSS6RA7HvU/qGxTnTVYcTWvRwhgYDhsTw=,tag:NqdmiliDIW4y1fqDVuS6zQ==,type:comment]
    #ENC[AES256_GCM,data:+eUfESf09WsHIBPI6h5In6g3e21QMNvWad59TLTqOdwvYm9k6ZkCbYBXMKXt4HzM7LfPgEUTeqWtIFOKHlk9DQeA1HHnHPlwbYnPqE58qaqViCYk66kC52z6EwgBb/RIbl2TLmfk2UH9J7Meo2KmaSv7xWwpcTubLihHPQ==,iv:dNbGNPhF0RF23zFQz+7ti9A+Xph4Bp9Vvis+nceRGVA=,tag:/14z74AVl11+F0xCU08KtA==,type:comment]
    #ENC[AES256_GCM,data:NBj9Vzd1JhbPvsgOfiiCH2W/BCvBJNfcquanLGXxDxGheKu/DqXYrKEk8Ema6YJ8WZYIRMTAP/ve8bHuEPOItBPXmxpfk54+zF5D2aVeBoE=,iv:Jkqakin1ArLbGMm2XRu2XO2smv8/cGLgAZHNsIQgNhI=,tag:sWc5zUtLMAIOeweoKtJl9Q==,type:comment]
    #ENC[AES256_GCM,data:cJq9CPBpnKaDD8BxWuBqv2jPj4E7w717vUl+GgeOKXVPZh0o1XkbkON+ofuryvwdFCp9VmBO,iv:fifyFNLmJWvA3oaoaxHLt/GFLZ7glTtWIBNRWMSsySk=,tag:jur+cSQfyLZFXgbJnx4t2Q==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:ctQvpKOJ7BW1Mi8=,iv:ug/UFeM939kggZ/Jkrql6GdzzDHhLVdYU08bjOW9K1o=,tag:j3j/h84JTVePBLUxmANo7g==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:WNuZY6sN/EaexF+4270aiHn/Kg==,iv:3L/UAfB0IpVVryZRluRFAk0ZbjXM/f11tPJ70XoaPqc=,tag:trd3EMQPOch+qOtWe4oeRw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:39zXWQAEKDBy++CyRUc+EHdpGRSw1sD5BbUhhH1/LgJRhgzAp8Z4nA==,iv:yZByF7Za+6GcfUSsPMCsHRcQlGT11C4IDUCQAw+2Dcc=,tag:ZAVCsggGffdGxaUDVXr8kA==,type:str]
    #ENC[AES256_GCM,data:Hwis7ot71oY9DNt6xZSqJodFIR/IX/8CykJOtEMWdvxzWwDGgq+Li2PDFO+U36VppQsDVluY8K4=,iv:L2mFYL9JlEllDnDtLKRy3W4yF5dLRTwdIdP8KotU+OQ=,tag:+IuswHVP50GrPsfwOMG18g==,type:comment]
    #ENC[AES256_GCM,data:fyhEKAlgkKGuBQTJjJXAAxqw1DGk5VCRPg==,iv:lGz/94m2HvdVVBx1pNjatIrkfW62tpmxCZSBylYirGw=,tag:gnbJJEVmZ8cfvDIiNh7gSQ==,type:comment]
    #ENC[AES256_GCM,data:ZesN/XM4p6d4Ae9TFNJlQK8J39MuKbRbO6JQvdTOY3j6ZP9nkRAr+gler/LH+1sEF/Ft4XCsSE4WK06j4++DiyyKwsAoTn9bkXAnfuY=,iv:5cF/wYFV5Z42v5/hMgGplgBpZPe9l5EW/1o2vaOB8Mo=,tag:F4LllYgDg3gyJmyYRRBg+g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:AkZERVeB7qKHBxYeG56wgVoURnJyxnkQBdhpry3kyQU0zN3763XJmX31pRYaJSLfJNrJFbEp,iv:GwsryXwg+nMs7XiKAJGuPlKlIX1qbjhtMSHbps3GvdA=,tag:vsWBPMvOe4iekgmdGXXJtg==,type:str]
    #ENC[AES256_GCM,data:AcfFH43RZip7rU77B+XZsfXyJIVwUKEf9wEW5x3yccYPVmLB/nvCWrmuetW20r+4dGLgyiXioUdzV+i3A8L9TWvF5XhdWoY=,iv:D9Cj9LKT52wKOMlgyKGBc6D+dMsEyDp0uQer4vbNzrI=,tag:NfdKI4T4sf5pnqA2GY1kRg==,type:comment]
    #ENC[AES256_GCM,data:Mp72ce6bcsfniKsMrW295fAJRm1g5AXdclBm1PfCQSqRX/UVbb7o1YQwnQCxfEz5X9IWtBd4,iv:ky6ridGRmJ2XsmzHDDm/EghVnCyflQTKc3nI8r1lmGY=,tag:ku24Ku2DpWPpsYyYm8P4Og==,type:comment]
    #ENC[AES256_GCM,data:YQsAui//Yu0nGwT04wrO1A5pgc2dzZFx1TDLKhBC8W1nZgI=,iv:VFjwg/IU38U7fpc7nydz9Kof+mMGvyvOwVHMQ99/NPs=,tag:PUKDjeIMT6+CgzUbylvJWQ==,type:comment]
    #ENC[AES256_GCM,data:FpikxNTlyiFwciSQ3wsgA7d6vSsLHVg3xZ0R4qtOoTgrRBlqSqOa,iv:XA3HExMGCS55zAuWNJmciElxVzj7caqe7SAfP34IPxA=,tag:uuoLoy1asBrtxik2PIhbmw==,type:comment]
    #ENC[AES256_GCM,data:oRAWN5uIOoNUHGYWZCU=,iv:8OYgHiosNwwtKDBCDqA1WHiICjrSDsToZpi+XNAbTBQ=,tag:aTYg7Th6hNMCyPtntsbh8A==,type:comment]
    PODNET: ENC[AES256_GCM,data:gCKcNgKsIdE3hVN66g==,iv:HmwxLPvTmTUtRczyJp3xdYwyXMYUewtijMpKbSmPvX8=,tag:HbhHqItG81DJcAorhNTgbQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:y6rZZNxsFf0ByUTLww==,iv:AYb9R6ouzuGMwz2NxHHphTyxAJiuroaazL8Hht38Uak=,tag:Aa+UWW+P2PTyuooTsJz20g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Du649A==,iv:huTDl+WWV3d8uxew0GLlPT2NVrRBYzAyf97/GTtK4/A=,tag:gACtkkQ6F03HBoDE867z1w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RW5heEtoalh0VTBMcFpC
            ZzhnalNxU3hTVWxROE1VQmhmcXhBWHJZbUJRCjJPWnpUS3IvZVdpaFhtd3N5TzEz
            cVhYYVYyak9xRnJQbDRvTVc4Z3VNdGsKLS0tIEpPdzZQNjk3ZndIbnJXeW0reU9G
            cWxBb3lQKytRK2lNazRhajBSR3d3dkUKfc7r/Gno2a1CXVMAw+1SCPVLmgNNFIxo
            tWTN/RpV4aF+BmkYm+t9K2IxE3ZPA1KxR7UU+3aAdUkCeyWkHN7orw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T18:12:37Z"
    mac: ENC[AES256_GCM,data:SXe9I/5JufdVD+kmB59rOZTdNfvTabB6V02v/Au6fYmn/M5DPzaEK6kNeZ1s1S/TvSQFi+ZTDX2214MxKGq860UveZAmb9GrHu4JE0To5k74ToA88RT+pef11I9VqtcZwZGe0F80PtmrXn0wpJ/TKedDmpxqTe8ahUlKcVkuRbU=,iv:IKUlHQfTN4nkshzlGm5deyAnNwAuL8YOm6VjFJlIKro=,tag:OolMBnc9yy5ClLmlGqNlFQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
