apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uSPSHpxhzJIK8C+Q9TeY0zxgtZEZjATBCB2zbn6Z4B3ZN4X8azNfcaZvN/IXFvridS66lXWriI3XXr4Zadg3a3aI7nOaHRrE0eh1pubTBxIXLSUElO8M2Gjx8T26alCGLDt52L7bTWvFi7nnhs3qDwnVhNxUr6N/2HpUbI5GhTiZkfvDTNcaEPCPFikIFzi8Jg0cOs6Xmb8AfTXXThslDIpdIY8Gl4wg5cbh1IPthB3/Zl/7ZAS4vIP2ycS3S5ajC63FRRNhqOpkJt+rfm+SUMQ3XHgwpguR2LwrMRvtSdJIjfOggDn3sdg+VeRADT8Hx3mV37vOvJcFBzciSkl4ZVHFNWJhdNDaqXt1PXaUvP0jPzUB3+InERCxrDmh4NMx,iv:OsdcYll6ISOa+30BxKzXR03oo8Oh/WOzZZPrOgsJ+RQ=,tag:OhpKYQU6DI0AADroUd9L0Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:eSgREsDVkDBaeDRKWCAWIn6vlNCa4uI9sY2IYClWTsJ6JFESaBrAKduIpvvjprhh4TdC3fCvvacxx5QdUYsjMZuNYHP95XObAF0sQjHtSDyi1ftPJbw7i6beVVnosUeAFsLOSkmnnl25KKKlYKssz7k8IArn6Aoza3XE0kkchaTldubwmlgpstfSNQ3vRVgc416EQ/PNyElOpdo9k14ki7ruOY1N4T9cSgWLvmly8RahAQImzCnjOr1b46AAn1xUOAUpp+aHUoJam0CvFQ==,iv:B10vgUmmvjg3quak2AQDSeFQ6G5Pi2jyFs+1E5iRqPQ=,tag:kKreF6F42XvRb1QS2l4G0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:7dHrEv/RUNTV+mfeQL0Zffy3EnSOFNA14uP/gcmY11008kghKJ/2lRV8h+HytPwtQFnecnilaWjP5cvGyMoQ7Ls4QwYzZLE5IbndbtwPV+DqSVVOnYCIbi+W9nMc9EtH/apHbaolh0hda+mzoSbWsNeCqINESx7Cb1IB59YaAbCsswApwLBuu2JyYj8k183vRv5VRibkmFyZaGxd9PWl/U6TRY4kqIq/zULL,iv:fYihYOcfwCFOXuP+pngJuuZQf3Q/6SY7PNCfs4CNKWA=,tag:PQBP3F/NoXMCZLX1H33r+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbnVJTzZRME5LejVHT003
            SjJHQ0VQcDZzVjBGMUZNb1hWUnNTUk1FYkNRClR5S0VTeEh1dHJ4Z2dnN2RnVUl5
            OW9UWHY4K0J2SGptZE1mS3IzQ0h0ZDgKLS0tIFVrYmFyNmJxeXdoS0ZYblRiK0wr
            YUdUODdqemN0cGN4NzByaGUwdDdKUnMK5ZUFxBrDcViIgMTHdquRVt9QKmXEmH7t
            F0eH9F3md2TgYT+ds3xJFUAjAEdrJkL98h7hxjMWRrDlCEsEAQWPwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:10:02Z"
    mac: ENC[AES256_GCM,data:NO64tUp2trddm2WGfGAf5h9Jo0abe4+Iu2xbaRo7cex4ZUgbeKfHVuY7ncc1z6puDnpp4HD+R7xAa6Ny8uMa5cwLYjTTb0z9I8BQTBXqIyvWM0jE1O2tjWIX2WNu7vaJ6L3LsS51yj41iVlAoYfPKdpYw2Wq50AhsN6BMUoUR28=,iv:TBzqHxJdj0dwIs3jL0hXKXLpRZtONiGMcl3amrHJk0A=,tag:7RfBWMe4Tx3pyC0KAMogUA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
