apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oIZrhhYnIZFxmGBTMr/+1dFUqDyfcX0owi84E8WokohUkfiDjT4hqbxhoFtOQdcKAGlJuSt45WqjX8kNMuSKCVZCyqElJXxrNvckfkXS+1XCXoIKB8+VKgmofsWpGwCCVWh7mre8W88yBf2mdZeQRCUhIvJwclduSQkWFHNHDhjiniGbrHwTxWzU8KkAeN9CzJpoul5Hq7Ag8uGn/5y64EoQquEG2f1yUH/xNmixmFc9Exyx8INdhZ42YucE9SPRll+MGQ+hxDl+P7jEAQ3rNY5YNNhe2W9t38dLJLdYOjytdzAHAZZgCf9JGsOReI0SbdpyPTwpuMMzY8srhFUBhQ+t08lJfrRNK11Kpo4doWKnQp+BqMuGFOBCPVJtrVGE,iv:unSJMP2cKX5jcFJakS1Y1F2bvcnh8psPAlm/aywkOfU=,tag:APEtZ8lCf7Z5R9kptRecjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PL0/z2jKOAS17L3Fo915Eu6PU6+JmAiBO/+tuH3zK3WznKAF9ztj9sjyeZBuVVbGIsGGgxxNCNIIo52Ip5V54z+cgZnWWlfbCX17+2+i1Gy1O55dlT9g/H6bnaKxpe36R9NXgBo5u4oXR5PLLahwh1EMAFmxeu2n4Cck2ce/CGHg6DKn0x9a9sIG9GhDOUczmA8lRSAqihQb+Rx5/hn9hVR/O80LiR7IqoR7v6miAb8xQOwpjQFA/ITrmba/CuxyQca20IUsX8QxjqjN4w==,iv:RGI8RHMGxWS1Rfjf0B3CpLHca3Tuf9E2S23cdjLZYVg=,tag:TCd2uwNcm48hXt4SPTIT0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:jwWNptco5+PIxdvxiOvSNSj2fkREfAnYjejWYVz/EjMPP8pAl0xGWbfiKMMbZuaiB7lvw7kduz7vfduPyYvNR9V475o2AwtwQV4uUwF0ovO/vZJuyzqMGLHtdL/Kv7wFrSveYz3QE7Q3cY3Zsjo4m06V0d3KXBazFXe61qBdrAaDSpbiW7IL5J158IuryoPF7E2NvNVpEDHp5dhsnm7re6XJO9553AWlWLT9,iv:dez/kfaoqm8boXrEUZbe43U0XObcFI92E0XHBg3DkWE=,tag:1CBiJKpOoEhXj1NKX4y/OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb1JBb1AyaEVBWUM3b3FO
            VVREMGErK2ZGd0hIdG9ENHlwMk1HcXMwWlV3CjY2a0YyYVVEQWpDcGYzUmJZMng4
            Rm1jZ25HMTQxTXZuZzFoTTJSVlI1dTgKLS0tIDBsQ3l2VnZhdGszdXYxcnBkNmxr
            cFBEUWE1ZFZRT29taWFXamdSazNHY0kKHTvsB2wsXoU1wOkNDgS5Vugy3zq97l6Z
            /aW5aJPf7NOhAc51Dh9fJQZPBJwkx+yeAg0BmXzMXfvGQy+D2yQ+QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T12:46:14Z"
    mac: ENC[AES256_GCM,data:7UwRXwrk/9X7t7IAxaAKOBgCp+jf++DfENVcfpLtctbCqTbzkuqL4CsTBLZZyVrd+DeedATRpVP224oMRTZmz1MaRUERiMDhTZukIz3EW3Pp/RXNNfFhn2390gvUBUYYyoxL6y4DECG4rmN5NnP0l+LZOd1Tc86LxXTqhXDMZHk=,iv:6lqLp55m/hvMBws5pmDdHGQR1+tew6tAeb2rNGa+amE=,tag:ge7A5IhxE0xqB1yg5yxLUg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
