apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a50jOo4KFdMh3Kpxtgi+xedt+EQVBv/1dH075YfDqGcP/BLu3eoW+63dfm5jydetUQeMpHyraMfiIsWyM9YPc8So8LJzeGpVp3bEcj/qoARc7fCCRbpvhfuiIOA5L2lEesxANoPxlZtN1u9a3OpBylstoCGSixOc6zGR4BTxHu14+3GFUC8VYfC//PKADD2ULue/UOVxjWvmrPPmVxnzQoFLbUvvGcgNiVl046RRJIinBhC7eCr0LMw5BPR9biRBI6VTyYVwQglOLyhBXXROrBexL1MTie1G6NGFmc7yB6/whmo8W+YeUNJKCeHL/bIwSpKHABQVovVB91jvOW7ufRK6VaYvvTPVFxVL/Y803naq/xMf7rCxoM3+qDh3E/vF,iv:lfqKmt5QapT3PJRS1eL3tLdtoJLkWMGd4sMI/dTFEfs=,tag:fmEhpun/n72uQg3w/bYD1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:C2o7K2+1zas5i3P5Lqmpgq3dn0zDXVqslvVzmC7Qzuyj4FLxO96SfzVmsDrCmoY+Y2oi8SLWz0rbsfXNV3yNligPrYOA1dpskjYMRzjVOXyeRr4IMHro3gVOKe5LTmogWmduK9/iXG999iv3FkxviJpp062O6KW9k1w0gdnx4zd8l1EvhAMHlf6O7tLFvLKl0VKAy4AqU0GECDOtB8De7ze+lJQ1VyGEvIHSv40cS1XrM2f1nv09+MVd5etDsmWgJnkh/oCXUaGPQiXcpQ==,iv:uezbGz7SUrkfaOCS8wTisxNKzUAMGiClvgnf0sS8FGg=,tag:EmCyf6piUh4FOol4c4BFWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:7WfvFbIItEjFs3um4JW0iNeq8hCcuuFvUA2mNd3kHVvAw7Vu++s9aRezX1cXXTUxAzmdcBpu12p9imadtt/kqNAa/O2+Hasnf6HaRDkR5/mN8nysqW6DGSELshIsXLKQwTqXoZyag1PgQ++ZQKr1zRLPW17W7Pe1FlU1dsatoJNSvxQt8XgXjLFIXsC83GeLDrXnzbOtwps6P7xBTx1Akf6oGBerYEgE5C/N,iv:g/dkGAPxsmDh+9vlVgjDggAQHCJwlDR/MUcArGv+/aM=,tag:R/otnFjv4r37nQW6xlieeA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MkVNbTlUSU1RWnRlNVB3
            RXBNcHExMjdNdGk2djREM011di9SeWlXQlU4CndyOXV2ZkpKN1dDeVJkeHNhU1J0
            N0llMXRqMUd4Uld4NHlhZkF4VlFtSHcKLS0tIHZVbEU0ZHNpZVV1bDJPTWZSb25N
            Ly92Sld1dzZ5ZXRnN2hwK1FuSTNjN2sK+sKbjiD25R06S/6ZNjcDqeYQk+3FjUw1
            YJ7K7exvYapE0eNLuX8W5OCUgg5sFbXw+JNcTXnPc9TTkw+3UYFRNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:55:31Z"
    mac: ENC[AES256_GCM,data:5KWACc8mfr7spkfRbFUHCkjX6zrxXZ6ociyQ9XwE6BnerLjAsbdqyYBthzIOTN5t4Gicc1EDUi2/Lyq8MucuZAHxlZIf7s26waKYN5TK3ApfxN66pR13EiouCGzBWSySnsPCs7htvmutIi6UfGyf7v15UrXny5EI5YVT9hbcgQc=,iv:A9cUCjNvJaOSAy/lZHSa4aSNZIP96oYdExD41zfLezQ=,tag:WwDUYvEukUg2bDCXgnMuew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
