apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-dokploy
  namespace: external-service
spec:
  interval: 5m
  chart:
    spec:
      chart: external-service
      version: 16.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    service:
      main:
        enabled: true
        externalIP: ${DOKPLOY_IP} 
        ports:
          https:
            enabled: true
            port: 443             
            protocol: tcp
        type: ExternalIP
    ingress:
      main:
        enabled: false            
