apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-service-dokploy
    namespace: external-service
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: external-service
            version: 16.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      service:
        main:
          enabled: true
          externalIP: ${DOKPLOY_IP}
          ports:
            main:
              enabled: true
              port: 3000
              protocol: http
          type: ExternalIP
      ingress:
        main:
          enabled: true
          ingressClassName: external
          hosts:
          - host: '${DOMAIN_1}'
            paths:
            - path: /
              pathType: Prefix
          - host: '*.${DOMAIN_1}'
            paths:
            - path: /
              pathType: Prefix
          integrations:
            certManager:
              certificateIssuer: domain-1-le-prod
              enabled: true
            traefik:
              enabled: false