apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XSBhseoc+v2HNwu+hbui4DDLhIvdh9r4lTAd09hPbrEizTuUPJaSxQ==,iv:UneUT0FYcURQxxemTYrQF/pImkryoV2r0hWtc3E44Uw=,tag:FDZwXqk+CGmHg+ksrug8Pg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a01iTDZINWIzNDNzSXJF
            ZTRNUmMzejlmSXlad21telpRSWlDOFIvbzFvCjZUL1I2K25IZ1llTkUyVFpoZzlp
            dHlGbld4WmJoYTFrSkRHMGduNERCNVUKLS0tIE1FSjRlK3NQQW9obmZXazQ2WFRT
            Wm0yeHpPZmlqc1dYemprRzdYWmpvMk0KThDjXtGtx5i+rs/vxYiWQWhAFTNfvWh+
            72zFREbSd/RttPYYPc4UJ0QCNdCVDwf4PC1k0WVPjD46X6RadSUx1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T12:08:12Z"
    mac: ENC[AES256_GCM,data:D7Dq0ANf4J70JQBIF0o78gR4kRzWyYrEootL1+tZKqXcrGvh2XYyxt/LclgKVPb48VkT40Nfp4k3HA6krWW8EnXVKytHTfdVboIC/BOKQNsuD09u3COCAUhUD7B7XCNf2q0GSLX/hKfFgj12c47cKm13WqcNjKwNjwbb/1sjRa8=,iv:ZqZ9h6cv5qysijE76Jb5NB858VEqV4XIeFiNvT1zq0Y=,tag:XfQuh1zSQvyaT8EONbBd+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
