apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:w1EtnOYxukXGBT/N5hwTbBH+sFt5CMEQqb13iN8NcvwVXRShLLWwew==,iv:wPbw6i69/ih3m93OEMF3onqdOSLvLfs7+Mse1QTtxCw=,tag:410WQuonqAGRTHZHk0LTJw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UElIY0hvTy82U2U3cWpE
            a1RxZ3VVTndrdXJmSUx6Q2hqdUM5OGlDeWtnCkFnVHhrVEhYTXpadjBMT3RXWVcr
            eTZFdFc3YU5UbEdTMEJOTU4zUCtUUzgKLS0tIHhOVnNZSWpQRWZhVHNJeU1LYmUx
            QVNZUVJyQVJyLytTc1NBSnExN3VVbjQKJ0qQW0Tx5NPx3TqT6f2qpdl5OnciSWNW
            5C2pUSDmTf789lLAfRBwOb3E/KyJx27gkyoraBGQg4SFdTEXMc4ydw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T19:42:10Z"
    mac: ENC[AES256_GCM,data:xWGGWvJgDR2ptl/ud4oPCJVTX+yaHyATG805EFyFIQgIs9/iuBqoAQMk9E1tqCZf0m2gAjLY+hg/DgLio/PxkbKW79JKVxZTXhJ0xU/nKm4/1REkB+c9v81Kmq6Jy8x6U3wztnZINpAvQEVrCM0+uOE0ngyUT5hO9WVWlXB9KSU=,iv:dvlvDFQ8YTJoNScJnwn0AaCtXbQfnWs+tDNXKJvpKkA=,tag:xXrvzwuFk/QWgUhTY75FkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
