apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: overseerr
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: overseerr
            version: 15.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-overseer"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: real-ip
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: plex.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 0 * * *
                  