apiVersion: v1
kind: Deployment
metadata:
  name: immich-machinelearning
  namespace: immich
spec:
  template:
    spec:
      containers:
        - name: immich-machinelearning
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 2
              memory: 4Gi
              nvidia.com/gpu: 1
