---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 27.1.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-authelia"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    cnpg:
      main:
        cluster:
          singleNode: true
        backups:
          enabled: true
          credentials: minio
          scheduledBackups:
            - name: daily-backup
              schedule: "0 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
            method: object_store
            credentials: minio
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 0 * * *
    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_KEY}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_KEY}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY}
    authelia:
      theme: auto
      totp:
        issuer: ${DOMAIN_0}
      authentication_backend:
        ldap:
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          tls:
            server_name: lldap.${DOMAIN_0}
          base_dn: DC=${DN},DC=${DC}
          attributes:
            username: uid
          additional_users_dn: ou=people
          users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          user: uid=admin,ou=people,dc=${DN},dc=${DC}  
          password: ${LLDAP_PASSWORD}
      access_control:   
        default_policy: deny                                                                           
        rules:                                     
        - domain:                                  
            - ${DOMAIN_0}                       
            - '*.${DOMAIN_0}'                    
          policy: two_factor                       
          subject:                                 
            - 'group:admin' 
        - domain:                                                      
            - 'chat.${DOMAIN_0}'                    
          policy: one_factor                      
          subject:                                 
            - 'group:ai_user'
        - domain:                                                      
            - 'stream.${DOMAIN_0}'                    
          policy: one_factor                      
          subject:                                 
            - 'group:stream_user'
        - domain:                                                      
            - 'ask.${DOMAIN_0}'                    
          policy: one_factor                      
          subject:                                 
            - 'group:stream_user'
      session:
        cookies:
          - domain: '${DOMAIN_0}'
            authelia_url: 'https://auth.${DOMAIN_0}'
            default_redirection_url: 'https://www.${DOMAIN_0}'
      regulation:
        find_time: 10m
        ban_time: 12h 
      notifier:                        
        smtp:      
          address: 'smtp://${SMTP_HOST}:587'                               
          username: ${SMTP_USER}
          password: ${SMTP_PASSWORD_AUTHELIA}
          sender: ${SMTP_USER}
          startup_check_address: ${SMTP_USER}           
          disable_html_emails: true               
          tls:                         
            server_name: ${SMTP_HOST}    