apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: comfyui
  namespace: comfyui
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    image:
      repository: yanwk/comfyui-boot
      tag: latest
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          main:
            enabled: true
            protocol: http
            port: 8188
            targetPort: 8188
    securityContext:
      container:
        PUID: 0 # Run as root
        runAsNonRoot: false # Allow running as root
        runAsUser: 0 # root user
        runAsGroup: 0 # root group
        readOnlyRootFilesystem: false # Needs to write to root FS? Set to false
      pod:
        fsGroup: 0 # Use root group for volume permissions
    ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: art.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    workload:
        main:
          podSpec:
            runtimeClassName: "nvidia"
            containers:
              main:
                resources:
                  limits:
                    nvidia.com/gpu: 1
