apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: code-server
    namespace: code-server
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: code-server
            version: 13.12.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      global:
        stopAll: false
      portal:
        open:
          enabled: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${CODE_SERVER_IP}