---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: romm
    namespace: romm
spec:
    interval: 5m
    chart:
        spec:
            chart: romm
            version: 13.9.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
                  IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}
                  OIDC_ENABLED: "true"
                  OIDC_PROVIDER: "authelia"
                  OIDC_CLIENT_ID: ${OIDC_ROMM_CLIENT_ID}
                  OIDC_CLIENT_SECRET: ${OIDC_ROMM_CLIENT_SECRET_INSECURE}
                  OIDC_REDIRECT_URI: "https://games.${DOMAIN_0}/api/oauth/openid"
                  OIDC_SERVER_APPLICATION_URL: "https://auth.${DOMAIN_0}"
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-romm"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: games.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 0 * * *
        library:
          enabled: true
          type: nfs
          path: ${GAMES_NFS_PATH}
          server: ${NAS_IP}
      metrics:
        main:
          enabled: false