apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: home-assistant
      version: 28.13.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16
    credentials:
      minio:
        type: s3
        url: "${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-home-assistant"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: ha.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    cnpg:
      main:
        cluster:
          singleNode: true
          credentials: minio
          scheduledBackups:
            - name: daily-backup
              schedule: "0 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: minio
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 10 1 * * *