apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu-operator
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/amd-gpu/amd-gpu-device/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster